### ISSUE TITLE
Peminjaman dan pengembalian tidak berjalan

### ISSUE THREAD

**Issue by Muhammad-Ikhwan-Fathulloh** [NadhiraAdhya/UTS_Perpustakaan_Nadhira#1]
Peminjaman dan pengembalian tidak berjalan, tidak ada button untuk melakukan aksi tersebut, silahkan perbaiki.

**Comment by NadhiraAdhya** [comment]
izin pa,apakah boleh diperbaiki lagi?


Nadhira Adhya

Pada Rab, 1 Mei 2024 23.22, Muhammad Ikhwan Fathulloh <
***@***.***> menulis:

**Comment by Muhammad-Ikhwan-Fathulloh** [comment]
Silahkan diperbaiki, jika sudah komen lagi disini agar saya cek

**Comment by NadhiraAdhya** [comment]
saya sudah perbaiki lagi,fungsi pengembaliaan dan peminjaman sudah
berfungsi,tetapi saya menggunakan code html semuanya apakah saya harus
membuat project baru dengan format php? atau hanya itu saja yang saya
perbaiki? dan apakah nilai saya akan di kurangi karna tidak menggunakan
php? tetapi oop nya saya sudah kerjakn semuanya

Nadhira Adhya

Pada Kam, 2 Mei 2024 00.19, Muhammad Ikhwan Fathulloh <
***@***.***> menulis:

**Comment by NadhiraAdhya** [comment]
mohon maaf pa,saya menunggu jawabnnya sebelum dl yang diberikan untuk bisa melakukan perbaikan saya ucapkan terimakasih atas perhatiannya sebelumnya

**Comment by Muhammad-Ikhwan-Fathulloh** [comment]
Gunakan kode php ya, perbaikan akan saya buka sampai besok hari untuk kelas 221PA

**Comment by NadhiraAdhya** [comment]
baik pa terimakasih

**Comment by NadhiraAdhya** [comment]
izin pa saya sudah melakukan perbaikan didalam project yang sama tetapi file yag berbeda,terimakasih atas perhatian dan pengertiannya pa

**Comment by Muhammad-Ikhwan-Fathulloh** [comment]
ok sip
